version: 2
jobs:
    build:
        docker:
        - image: andreacensi/mcdp_books:duckuments@sha256:360b501d4cc3c0c9d7fb6053559267696f215eded259c5f81cfe04d4d191c785
          environment:
              COLUMNS: 160
              TERM: xterm-256color
              EXTRA_MCDP_RENDER_OPTIONS: --ignore_ref_errors

        resource_class: large
        steps:
        - checkout
        - run:
            name: Download resources
            command: |
              git submodule sync --recursive
              git submodule update --init --recursive

        - run:
            name: Compile
            command: make compile-native-ci

        - run:
            name: Link check
            command: |
                . /project/deploy/bin/activate && make linkcheck || true

        - run:
            when: always
            name: Package artifacts
            command:  |
                find duckuments-dist -name '*.old' -delete
                make package-artifacts

        - store_artifacts:
              path: out/package.tgz
              destination: out/package.tgz


        - store_artifacts:
              path: duckuments-dist
              destination: duckuments-dist


        - test-results-store:
            path: duckuments-dist/junit
